import 'package:flutter/material.dart';
import 'package:islami_app/features/layout_screen/quran_Tap/view/widget/surah_name_and_number_of_verses.dart';
import 'package:provider/provider.dart';

import '../../../../../api manager/api_manager.dart';
import '../../../../details_screen/quran/presentation/view model/details_quran_view_model.dart';
import '../../../provider/settings_provider.dart';
import '../view model/quran_tap_view_model.dart';

class QuranTapBody extends StatelessWidget {
   QuranTapBody({super.key});
  final List<String> numberOfVerses = [
    "7",
    "286",
    "200",
    "176",
    "120",
    "165",
    "206",
    "75",
    "129",
    "109",
    "123",
    "111",
    "43",
    "52",
    "99",
    "128",
    "111",
    "110",
    "98",
    "135",
    "112",
    "78",
    "118",
    "64",
    "77",
    "227",
    '93',
    '88',
    '69',
    '60',
    '34',
    '30',
    '73',
    '54',
    '45',
    '83',
    '182',
    '88',
    '75',
    '85',
    '54',
    '53',
    '89',
    '59',
    '37',
    '35',
    '38',
    '29',
    '18',
    '45',
    '60',
    '49',
    '62',
    '55',
    '78',
    '96',
    '29',
    '22',
    '24',
    '13',
    '14',
    '11',
    '11',
    '18',
    '12',
    '12',
    '30',
    '52',
    '52',
    '44',
    '28',
    '28',
    '20',
    '56',
    '40',
    '31',
    '50',
    '40',
    '46',
    '42',
    '29',
    '19',
    '36',
    '25',
    '22',
    '17',
    '19',
    '26',
    '30',
    '20',
    '15',
    '21',
    '11',
    '8',
    '5',
    '19',
    '5',
    '8',
    '8',
    '11',
    '11',
    '8',
    '3',
    '9',
    '5',
    '4',
    '6',
    '3',
    '6',
    '3',
    '5',
    '4',
    '5',
    '6'
  ];
  final List<String> surahNames = [
    "ٱلْفَاتِحَةِ",
    "البَقَرَةِ",
    "آلِ عِمۡرَانَ",
    "النِّسَاءِ",
    "المَائـِدَةِ",
    "الأَنۡعَامِ",
    "الأَعۡرَافِ",
    "الأَنفَالِ",
    "التَّوۡبَةِ",
    "يُونُسَ",
    "هُودٍ",
    "يُوسُفَ",
    "الرَّعۡدِ",
    "إِبۡرَاهِيمَ",
    "الحِجۡرِ",
    "النَّحۡلِ",
    "الإِسۡرَاءِ",
    "الكَهۡفِ",
    "مَرۡيَمَ",
    "طه",
    "الأَنبِيَاءِ",
    "الحَجِّ",
    "المُؤۡمِنُونَ",
    "النُّورِ",
    "الفُرۡقَانِ",
    "الشُّعَرَاءِ",
    "النَّمۡلِ",
    "القَصَصِ",
    "العَنكَبُوتِ",
    "الرُّومِ",
    "لُقۡمَانَ",
    "السَّجۡدَةِ",
    "الأَحۡزَابِ",
    "سَبَإٍ",
    "فَاطِرٍ",
    "يسٓ",
    "الصَّافَّاتِ",
    "صٓ",
    "الزُّمَرِ",
    "غَافِرٍ",
    "فُصِّلَتۡ",
    "الشُّورَىٰ",
    "الزُّخۡرُفِ",
    "الدُّخَانِ",
    "الجَاثِيَةِ",
    "الأَحۡقَافِ",
    "مُحَمَّدٍ",
    "الفَتۡحِ",
    "الحُجُرَاتِ",
    "قٓ",
    "الذَّارِيَاتِ",
    "الطُّورِ",
    "النَّجۡمِ",
    "القَمَرِ",
    "الرَّحۡمَٰن",
    "الوَاقِعَةِ",
    "الحَدِيدِ",
    "المُجَادلَةِ",
    "الحَشۡرِ",
    "المُمۡتَحنَةِ",
    "الصَّفِّ",
    "الجُمُعَةِ",
    "المُنَافِقُونَ",
    "التَّغَابُنِ",
    "الطَّلَاقِ",
    "التَّحۡرِيمِ",
    "المُلۡكِ",
    "القَلَمِ",
    "الحَاقَّةِ",
    "المَعَارِجِ",
    "نُوحٍ",
    "الجِنِّ",
    "المُزَّمِّلِ",
    "المُدَّثِّرِ",
    "القِيَامَةِ",
    "الإِنسَانِ",
    "المُرۡسَلَاتِ",
    "النَّبَإِ",
    "النَّازِعَاتِ",
    "عَبَسَ",
    "التَّكۡوِيرِ",
    "الانفِطَارِ",
    "المُطَفِّفِينَ",
    "الانشِقَاقِ",
    "البُرُوجِ",
    "الطَّارِقِ",
    "الأَعۡلَىٰ",
    "الغَاشِيَةِ",
    "الفَجۡرِ",
    "البَلَدِ",
    "الشَّمۡسِ",
    "اللَّيۡلِ",
    "الضُّحَىٰ",
    "الشَّرۡحِ",
    "التِّينِ",
    "العَلَقِ",
    "القَدۡرِ",
    "البَيِّنَةِ",
    "الزَّلۡزَلَةِ",
    "العَادِيَاتِ",
    "القَارِعَةِ",
    "التَّكَاثُرِ",
    "العَصۡرِ",
    "الهُمَزَةِ",
    "الفِيلِ",
    "قُرَيۡشٍ",
    "المَاعُونِ",
    "الكَوۡثَرِ",
    "الكَافِرُونَ",
    "النَّصۡرِ",
    "المَسَدِ",
    "الإِخۡلَاصِ",
    "الفَلَقِ",
    "النَّاسِ"
  ];

  @override
  Widget build(BuildContext context) {
    var settingsProvider = Provider.of<SettingsProvider>(context);
    var quranTapViewModel = Provider.of<DetailsQuranViewModel>(context);
    return Expanded(
        flex: 3,
        child: FutureBuilder(
          future: ApiManager.getNamesSurahs(
              settingsProvider.languageCode == "en" ? "eng" : "ar"),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(child: CircularProgressIndicator());
            } else if (snapshot.hasError ||
                snapshot.data?.isEmpty == true) {
              return const Center(
                  child: Text("something went wrong please try later"));
            }
            return ListView.builder(
              itemBuilder: (context, index) => SurahNameAndNumberOfVerses(
                  suraNumber: index,
                  isSelectedSurahBookMark: quranTapViewModel.getSelectedSurahBookMark() == index,
                  surahName: snapshot.data![index].name ?? "",
                  startPage: snapshot.data?[index].startPage ?? 0,
                  endPage: snapshot.data?[index].endPage ?? 0,
                  numberOfVerses: int.parse(numberOfVerses[index]),
                  surahNameTashkil: surahNames[index]),
              itemCount: snapshot.data?.length,
            );
          },
        ));
  }
}
